include $(TOPDIR)/rules.mk

PKG_NAME:=rtp2httpd-minimal

RELEASE_VERSION:=3.11.0

PKG_VERSION:=$(shell echo "$(RELEASE_VERSION)" | sed 's/-\([a-z]*\)\.\([0-9]*\)/_\1\2/g')
PKG_RELEASE:=1
PKG_MAINTAINER:=Stackie Jia <jsq2627@gmail.com>
PKG_LICENSE:=GPL-2.0-or-later
PKG_LICENSE_FILES:=LICENSE

PKG_FIXUP:=cmake

export RELEASE_VERSION

PKG_SOURCE:=rtp2httpd-v$(RELEASE_VERSION).tar.gz
PKG_SOURCE_URL:=https://codeload.github.com/stackia/rtp2httpd/tar.gz/v$(RELEASE_VERSION)?
PKG_HASH:=1834c1ad9f650948a707b673c66415c11b6f13d289b5ddc863b844afff80da99

include $(INCLUDE_DIR)/package.mk
include $(INCLUDE_DIR)/cmake.mk

define Package/rtp2httpd-minimal
	SECTION:=net
	CATEGORY:=Network
	TITLE:=Multicast RTP/UDP to Unicast HTTP stream converter (minimal)
	URL:=https://github.com/stackia/rtp2httpd
endef

define Package/rtp2httpd-minimal/description
	Minimal build of rtp2httpd focused on direct RTP/UDP to HTTP streaming.
	Web UI, status page, M3U/EPG, RTSP, HTTP proxy, snapshot, FCC and FEC are disabled.
endef

CMAKE_OPTIONS += \
	-DCMAKE_BUILD_TYPE=MinSizeRel \
	-DENABLE_AGGRESSIVE_OPT=OFF \
	-DRTP2HTTPD_MINIMAL_BUILD=ON \
	-DRTP2HTTPD_ENABLE_SIZE_OPTIMIZATIONS=ON

define Package/rtp2httpd-minimal/conffiles
/etc/config/rtp2httpd
/etc/rtp2httpd.conf
endef

define Package/rtp2httpd-minimal/install
	$(INSTALL_DIR) $(1)/etc/init.d $(1)/etc/config $(1)/usr/bin
	$(INSTALL_CONF) ./files/rtp2httpd.conf $(1)/etc/config/rtp2httpd
	$(INSTALL_CONF) $(PKG_BUILD_DIR)/rtp2httpd.conf $(1)/etc
	$(INSTALL_BIN) ./files/rtp2httpd.init $(1)/etc/init.d/rtp2httpd
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/rtp2httpd $(1)/usr/bin
endef

$(eval $(call BuildPackage,rtp2httpd-minimal))
